### ISSUE TITLE
MacOS: "T" label not updated when changing the technology

### ISSUE THREAD

**Issue by klayoutmatthias** [KLayout/klayout#1254]
This is a follow-up ticket for the issue mentioned by @lukasc-ubc here: https://github.com/KLayout/klayout/issues/1250.

**Comment by klayoutmatthias** [comment]
I have some feeling that this problem is going to be fixed together with #1253, but that needs confirmation.

**Comment by Kazzz-S** [comment]
I've merged ab8cfee1 to 1d8568e4, and rebuilt two DMGs with Homebrew in Monterey. Files are [here](https://www.dropbox.com/sh/chzycnydbhwu2p3/AACddSZfRRc09HFP0OmLqCkGa?dl=0)(Dropbox link).

![issue1254-01](https://user-images.githubusercontent.com/16847255/214460126-c17229aa-f9d2-4885-a969-6f1c270d3213.png)

![issue1254-02](https://user-images.githubusercontent.com/16847255/214460306-ee8264bd-c55a-400f-8faa-6940d36787d1.png)

![issue1254-03](https://user-images.githubusercontent.com/16847255/214460336-2ab69139-e4b1-47a3-af12-43660f983fd3.png)

![issue1254-04](https://user-images.githubusercontent.com/16847255/214460368-a637cfc3-195c-4962-aaa1-5101a54c15d3.png)

![issue1254-05](https://user-images.githubusercontent.com/16847255/214460415-df26001d-4045-4836-b091-df6d138de73c.png)

![issue1254-06](https://user-images.githubusercontent.com/16847255/214460596-118825a5-9c6e-4f2a-8a79-e25392a6d05e.png)

**Comment by lukasc-ubc** [comment]
Tried it and the problem persists.  T=empty, then I select the 2nd library, and then T=EBeam and the libraries show up.

**Comment by klayoutmatthias** [comment]
Hi Lukas,

thanks for that feedback. 

I could reproduce and debug the problem on my Catalina VirtualBox instance. After fixing some events that had not been sent, I think the problem should be solved now. I tried number of different ways (load layouts, create new layouts, replace layouts etc.) and I could no longer see the issue.

@kazzz maybe you can help (a last time I hope) and try out the issue-1259 branch. If that works, I'll release it with 0.28.4.

Thanks and best regards,

Matthias
